spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
      show_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/apigatewayDB?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 900505
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
